Rebuild for CUDA 12 w/arch + Windows support
conda-forge/openmm-feedstock pull request #121
Opened 2023-11-28 09:07 UTC by RaulPPelaez

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is #119 reopened without merge conflicts.

2023-11-28 10:33 UTC, jakirkham reviewed
Thanks Raul! 🙏

Had a minor suggestion below to help with a couple CI failures that cropped up

2023-11-28 10:33 UTC, jakirkham commented on recipe/meta.yaml
> +    - {{ compiler('cuda') }}  # [linux or win]
To ensure the CUDA compiler is only added when used, would suggest this tweak to the selector

```suggestion
    - {{ compiler('cuda') }}  # [(linux or win) and cuda_compiler != "None"]
```

2023-11-28 17:09 UTC, mikemhenry approved these changes

2023-11-28 17:09 UTC, mikemhenry commented
LGTM

2023-11-28 21:54 UTC, mikemhenry requested changes
I changed my mind, the build number needs to be bumped

2023-11-28 21:55 UTC, mikemhenry commented
@conda-forge-admin, please rerender

2023-11-28 21:56 UTC, mikemhenry approved these changes

2023-11-28 23:47 UTC, jakirkham commented
Thanks Mike! 🙏

Looks like it passes 🎉

2023-11-29 16:30 UTC, mikemhenry commented
Forgot to add the automerge label :upside_down_face:

2023-11-29 16:31 UTC, merged